version: 1.0.{build}
configuration: Debug
platform: Net40
before_build:
- nuget restore ICSharpCode.AvalonEdit.sln
build:
  project: ICSharpCode.AvalonEdit.sln
  parallel: true
  verbosity: minimal
after_test:
- python ICSharpCode.AvalonEdit.Tests\tidy.py
